set:
  features: false
  train: false
  eval: true

path:
  root_dir:  E:/Pythonproject/dcase-few-shot-bioacoustic
  train_dir: E:/Pythonproject/dcase-few-shot-bioacoustic/baselines/deep_learning/Development_Set/Training_Set/
  eval_dir:  E:/Pythonproject/dcase-few-shot-bioacoustic/baselines/deep_learning/Development_Set/Validation_Set/
  feat_path: ${path.root_dir}/Features
  feat_train: ${path.feat_path}/feat_train
  feat_eval:  ${path.feat_path}/feat_eval
  Model: ${path.root_dir}/model_weights
  best_model: ${path.Model}/best_model.pth
  last_model: ${path.Model}/last_model.pth

features:
  seg_len: 0.200
  hop_seg: 0.100
  eps: 2.220446049250313e-16
  fmax: 11025
  fmin: 50
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
  
train:
  num_classes: 15
  n_shot: 5
  k_way : 5
  device: cuda
  lr_rate: 0.001
  scheduler_gamma: 0.5
  scheduler_step_size: 10
  epochs: 2
  num_episodes: 2000
  encoder: Protonet  # Protonet or Resnet
eval:
  samples_neg: 50
  iterations: 10
  query_batch_size: 8
  negative_set_batch_size : 16
  threshold: 0.45



